#!/usr/bin/env sh

while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "Direct pushes to main are forbidden. Create a custom branch and open a PR."
    exit 1
  fi
done
